### ISSUE TITLE
Unable to refund payments from admin dashboard

### ISSUE THREAD

**Issue by sent-hil** [Affirm/spree_affirm#15]
Hello,

<img width="640" alt="affirm_payment" src="https://user-images.githubusercontent.com/164864/54851085-21641500-4ca6-11e9-8183-1933adbdae64.png">

In this screenshot above admin dashboard: https://take.ms/72BDp, you can see there's an Affirm payment, however there's no link to refund. Compared that with this below screenshot for payment made with a credit card:

<img width="640" alt="cc_payment" src="https://user-images.githubusercontent.com/164864/54851109-3345b800-4ca6-11e9-9f50-36b40059c78a.png">

Looking at the code I have tracked it down to this line: https://github.com/Affirm/spree_affirm/blob/master/app/models/spree/affirm_checkout.rb#L94. Not sure I understand the logic here. A fully paid order wouldn't be in 'credit_owed' state unless there's a refund created, which you can't create it f the link doesn't show up.

Removing that line fixes it, but want to make sure I don't break something else.

Any help is appreciated. Thanks!

**Comment by hf2186** [comment]
@sent-hil Removing that does fix it and it shouldn't break anything based on a quick review. 

However, the correct way of doing refunds is to first create an adjustment on the order, then process the payment difference, that way you order doesn't remain in a credit owed state. You can also handle this by either canceling the order or doing a refund through the spree RMA system.

**Comment by sent-hil** [comment]
@hf2186 that's a good point, will create an adjustment first, thank you.
